/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import javax.swing.JOptionPane;
import java.util.logging.*;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imant
 */
public class Member extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    public Member() {
        initComponents();
        setResizable(false);
setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        avatar_NoBorder2 = new Components.Avatar_NoBorder();
        jLabel2 = new javax.swing.JLabel();
        btnDashboard1 = new Components.CustomButton();
        btnAuthors1 = new Components.CustomButton();
        btnMembers1 = new Components.CustomButton();
        btnBooks1 = new Components.CustomButton();
        btnLogout1 = new Components.CustomButton();
        roundedPanel1 = new Components.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMemberId = new javax.swing.JTextField();
        txtMemberName = new javax.swing.JTextField();
        txtMemberEmail = new javax.swing.JTextField();
        txtMemberContact = new javax.swing.JTextField();
        roundedImageComponent1 = new Components.RoundedImageComponent();
        customButton1 = new Components.CustomButton();
        customButton2 = new Components.CustomButton();
        customButton3 = new Components.CustomButton();
        jLabel7 = new javax.swing.JLabel();
        txtMemberAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        member_tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 29, 61));

        jPanel4.setBackground(new java.awt.Color(0, 53, 102));

        avatar_NoBorder2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elite Library");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(avatar_NoBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar_NoBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnDashboard1.setText("Dashboard");
        btnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard1ActionPerformed(evt);
            }
        });

        btnAuthors1.setText("Authors");
        btnAuthors1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthors1ActionPerformed(evt);
            }
        });

        btnMembers1.setText("Members");
        btnMembers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembers1ActionPerformed(evt);
            }
        });

        btnBooks1.setText("BOOKS");
        btnBooks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooks1ActionPerformed(evt);
            }
        });

        btnLogout1.setText("LOG OUT");
        btnLogout1.setButtonColor(new java.awt.Color(255, 51, 51));
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnAuthors1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMembers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBooks1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAuthors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMembers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBooks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        roundedPanel1.setBackground(new java.awt.Color(0, 29, 61));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member ID");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member Name");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No");

        txtMemberId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtMemberName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtMemberEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtMemberContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        roundedImageComponent1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/ai-generated-8734944_1280.png"))); // NOI18N

        customButton1.setText("INSERT");
        customButton1.setButtonColor(new java.awt.Color(0, 255, 102));
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });

        customButton2.setText("UPDATE");
        customButton2.setButtonColor(new java.awt.Color(0, 153, 255));
        customButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton2ActionPerformed(evt);
            }
        });

        customButton3.setText("DELETE");
        customButton3.setButtonColor(new java.awt.Color(255, 0, 51));
        customButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        txtMemberAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMemberAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtMemberContact, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtMemberEmail)
                    .addComponent(txtMemberName)
                    .addComponent(txtMemberId))
                .addGap(145, 145, 145)
                .addComponent(roundedImageComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roundedImageComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundedPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMemberEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMemberContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMemberAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        member_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(member_tb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
       Dashboard dasboardFrame = new Dashboard (); // Create an instance of DasboardForm
    dasboardFrame.setVisible(true); // Show the DasboardForm frame
    dasboardFrame.setLocationRelativeTo(null); // Center the window
    this.dispose();
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnAuthors1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthors1ActionPerformed
        Author authorFrame = new Author(); // Create an instance of AuthorForm
    authorFrame.setVisible(true); // Show the AuthorForm frame
    authorFrame.setLocationRelativeTo(null); // Center the window
    this.dispose();
    }//GEN-LAST:event_btnAuthors1ActionPerformed

    private void btnMembers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembers1ActionPerformed
        Member memberFrame = new Member();
        memberFrame.setVisible(true);
        memberFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMembers1ActionPerformed

    private void btnBooks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooks1ActionPerformed
       Book bookFrame = new Book();
        bookFrame.setVisible(true);
        bookFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBooks1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    // If user clicks Yes, proceed with logout
    if (choice == JOptionPane.YES_OPTION) {
        LoginForm loginFrame = new LoginForm();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void loadMemberData() {
    dbconnection dbcon = dbconnection.getInstance();
    Connection con = dbcon.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    try {
        // Prepare SQL query to fetch all members
        String sql = "SELECT * FROM member";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        // Get table model from "member_tb" and clear existing data
        DefaultTableModel model = (DefaultTableModel) member_tb.getModel();
        model.setRowCount(0); // Remove old data

        // Loop through the result set and add data to JTable
        while (rs.next()) {
            String memberId = rs.getString("member_id");
            String memberName = rs.getString("member_name");
            String email = rs.getString("email");
            String contact = rs.getString("contact");
            String address = rs.getString("address");

            // Add row to JTable
            model.addRow(new Object[]{memberId, memberName, email, contact, address});
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Member.class.getName()).log(Level.SEVERE, "Error loading member data", ex);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, "Error closing resources", ex);
        }
    }
}
    
    private void clearFields() {
    txtMemberId.setText("");
    txtMemberName.setText("");
    txtMemberEmail.setText("");
    txtMemberContact.setText("");
    txtMemberAddress.setText("");
    }
    
    
    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
         dbconnection dbcon = dbconnection.getInstance();
    Connection con = dbcon.getConnection();
    PreparedStatement pst = null;

    try {
        // Get values from text fields
        String memberId = txtMemberId.getText().trim();
        String memberName = txtMemberName.getText().trim();
        String email = txtMemberEmail.getText().trim();
        String contact = txtMemberContact.getText().trim();
        String address = txtMemberAddress.getText().trim();

        // Input validation
        if (memberId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Member ID is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberId.requestFocus();
            return;
        }

        if (memberName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Member name is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberName.requestFocus();
            return;
        }

        // Basic email validation
        if (email.isEmpty() || !email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberEmail.requestFocus();
            return;
        }

        if (contact.isEmpty() || !contact.matches("\\d+")) {  // Ensures contact is numeric
            JOptionPane.showMessageDialog(this, "Please enter a valid contact number", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberContact.requestFocus();
            return;
        }

        if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberAddress.requestFocus();
            return;
        }

        // Check if connection is valid
        if (con == null || con.isClosed()) {
            JOptionPane.showMessageDialog(this, "Database connection is not available", "Connection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if Member ID already exists
        PreparedStatement checkStmt = con.prepareStatement("SELECT member_id FROM member WHERE member_id = ?");
        checkStmt.setString(1, memberId);
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Member ID already exists", "Insert Error", JOptionPane.ERROR_MESSAGE);
            txtMemberId.requestFocus();
            return;
        }

        // Prepare and execute insert statement
        pst = con.prepareStatement("INSERT INTO member (member_id, member_name, email, contact, address) VALUES (?, ?, ?, ?, ?)");

        pst.setString(1, memberId);
        pst.setString(2, memberName);
        pst.setString(3, email);
        pst.setString(4, contact);
        pst.setString(5, address);

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Member Record Inserted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadMemberData();  // Refresh the table
            clearFields();     // Clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "Failed to insert record", "Insert Error", JOptionPane.WARNING_MESSAGE);
        }

    } catch (SQLException ex) {
        String errorMessage = "Error inserting record: " + ex.getMessage();
        JOptionPane.showMessageDialog(this, errorMessage, "Database Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Member.class.getName()).log(Level.SEVERE, errorMessage, ex);
    } finally {
        try {
            if (pst != null) {
                pst.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, "Error closing statement", ex);
        }
    }
    }//GEN-LAST:event_customButton1ActionPerformed

    private void customButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton2ActionPerformed
       dbconnection dbcon = dbconnection.getInstance();
    Connection con = dbcon.getConnection();
    PreparedStatement pst = null;

    try {
        // Get values from text fields
        String memberId = txtMemberId.getText().trim();
        String memberName = txtMemberName.getText().trim();
        String email = txtMemberEmail.getText().trim();
        String contact = txtMemberContact.getText().trim();
        String address = txtMemberAddress.getText().trim();

        // Input validation
        if (memberId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Member ID is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberId.requestFocus();
            return;
        }

        if (memberName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Member name is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberName.requestFocus();
            return;
        }

        if (email.isEmpty() || !email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberEmail.requestFocus();
            return;
        }

        if (contact.isEmpty() || !contact.matches("\\d+")) { // Ensuring contact contains only numbers
            JOptionPane.showMessageDialog(this, "Please enter a valid contact number", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberContact.requestFocus();
            return;
        }

        // Check if connection is valid
        if (con == null || con.isClosed()) {
            JOptionPane.showMessageDialog(this, "Database connection is not available", "Connection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the record exists
        PreparedStatement checkStmt = con.prepareStatement("SELECT member_id FROM member WHERE member_id = ?");
        checkStmt.setString(1, memberId);
        ResultSet rs = checkStmt.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Member ID does not exist", "Update Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Prepare and execute update statement
        pst = con.prepareStatement("UPDATE member SET member_name = ?, email = ?, contact = ?, address = ? WHERE member_id = ?");
        pst.setString(1, memberName);
        pst.setString(2, email);
        pst.setString(3, contact);
        pst.setString(4, address);
        pst.setString(5, memberId);

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Record Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadMemberData();  // Refresh the table
            clearFields();  // Clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "No records were updated", "Update Error", JOptionPane.WARNING_MESSAGE);
        }

    } catch (SQLException ex) {
        String errorMessage = "Error updating record: " + ex.getMessage();
        JOptionPane.showMessageDialog(this, errorMessage, "Database Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Member.class.getName()).log(Level.SEVERE, errorMessage, ex);
    } finally {
        try {
            if (pst != null) {
                pst.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, "Error closing statement", ex);
        }
    }
    }//GEN-LAST:event_customButton2ActionPerformed

    private void customButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton3ActionPerformed
        dbconnection dbcon = dbconnection.getInstance();
    Connection con = dbcon.getConnection();
    PreparedStatement pst = null;

    try {
        // Get the Member ID from the text field
        String memberId = txtMemberId.getText().trim();

        // Input validation
        if (memberId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Member ID is required", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtMemberId.requestFocus();
            return;
        }

        // Check if connection is valid
        if (con == null || con.isClosed()) {
            JOptionPane.showMessageDialog(this, "Database connection is not available", "Connection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Check if the record exists
        PreparedStatement checkStmt = con.prepareStatement("SELECT member_id FROM member WHERE member_id = ?");
        checkStmt.setString(1, memberId);
        ResultSet rs = checkStmt.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Member ID does not exist", "Delete Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Prepare and execute delete statement
        pst = con.prepareStatement("DELETE FROM member WHERE member_id = ?");
        pst.setString(1, memberId);

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadMemberData();  // Refresh the table
            clearFields();  // Clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "No records were deleted", "Delete Error", JOptionPane.WARNING_MESSAGE);
        }

    } catch (SQLException ex) {
        String errorMessage = "Error deleting record: " + ex.getMessage();
        JOptionPane.showMessageDialog(this, errorMessage, "Database Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Member.class.getName()).log(Level.SEVERE, errorMessage, ex);
    } finally {
        try {
            if (pst != null) {
                pst.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, "Error closing statement", ex);
        }
    }
    }//GEN-LAST:event_customButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Avatar_NoBorder avatar_NoBorder2;
    private Components.CustomButton btnAuthors1;
    private Components.CustomButton btnBooks1;
    private Components.CustomButton btnDashboard1;
    private Components.CustomButton btnLogout1;
    private Components.CustomButton btnMembers1;
    private Components.CustomButton customButton1;
    private Components.CustomButton customButton2;
    private Components.CustomButton customButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable member_tb;
    private Components.RoundedImageComponent roundedImageComponent1;
    private Components.RoundedPanel roundedPanel1;
    private javax.swing.JTextField txtMemberAddress;
    private javax.swing.JTextField txtMemberContact;
    private javax.swing.JTextField txtMemberEmail;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtMemberName;
    // End of variables declaration//GEN-END:variables
}
